site_name: SEED Platform&trade; Documentation
repo_url: https://github.com/SEED-platform/seed

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: 'images/icon-city.svg'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: 'en'
  favicon: 'images/favicon.ico'
  icon:
    admonition:
      note: material/border-none-variant
    repo: fontawesome/brands/github
  feature:
    # tabs: true
    - content.code.copy
    - content.code.view
    - content.code.highlight
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 0

extra_css:
  - 'stylesheets/extra.css'

nav:
  - Home: 'index.md'
  - Getting Started: 'getting_started.md'
  - Documentation:
      - Release Notes: 'release_notes.md'
      - User Documentation:
        - Overview: 'user_doc_overview.md'
        - Getting Started: 'user_doc_getting_started.md'
        - Data Import: 'user_doc_data_import.md'
        - Feature Documentation: 'user_doc_features.md'
      - Developer Documentation: 'developer_resources.md'
      - Known Issues: 'known_issues.md'
  - News: 'news.md'
  - Hosting:
      - Requesting Test Instance: 'test_instance_request.md'
      - SEED Technical Allies: 'technical_ally.md'
      - Hosting Provider Process: 'hosting_requirements.md'
      - App Developers: 'app_developer_requirements.md'
  - Contact: 'contact.md'
  - References: 'references.md'
  - FAQ:
      - 'Features':
          - 'Geocoding': 'faq/features/geocoding.md'
          - 'Inventory Management': 'faq/features/inventory_management.md'
          - 'Miscellaneous': 'faq/features/misc.md'
      - 'Hosting': 'faq/hosting.md'
      - 'Industry Involvement': 'faq/industry_involvement.md'
      - 'Security': 'faq/security.md'

plugins:
  - redirects:
      redirect_maps:
        'lbnl.md': 'test_instance_request.md'
  - search
            