site_name: SEED Platform&trade; Documentation

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: 'images/icon-city.svg'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: 'en'
  favicon: 'images/favicon.ico'
  # feature:
  #   tabs: true

extra_css:
  - 'stylesheets/extra.css'

nav:
  - Home: 'index.md'
  - Getting Started: 'getting_started.md'
  - Documentation: 
    - Release Notes: 'release_notes.md'
    - User Documentation: 'documentation.md'
    - Developer Documentation: 'developer_resources.md'
    - Known Issues: 'known_issues.md'
  - News: 'news.md'
  - Hosting:
    - Requesting Test Instance: 'test_instance_request.md'
    - SEED Technical Allies: 'technical_ally.md'
    - Hosting Provider Process: 'hosting_requirements.md'
    - App Developers: 'app_developer_requirements.md'
  - Contact: 'contact.md'
  - References: 'references.md'
  - FAQ:
    - 'Features':
      - 'Geocoding': 'faq/features/geocoding.md'
      - 'Inventory Management': 'faq/features/inventory_management.md'
      - 'Miscellaneous': 'faq/features/misc.md'
    - 'Hosting': 'faq/hosting.md'
    - 'Industry Involvement': 'faq/industry_involvement.md'
    - 'Security': 'faq/security.md'

plugins:
    - redirects:
        redirect_maps:
            'lbnl.md': 'test_instance_request.md'
            