site_name: SEED Platform&trade; Documentation

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: 'images/icon-city.svg'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: 'en'
  favicon: 'images/favicon.ico'
  # feature:
  #   tabs: true

extra_css:
  - 'stylesheets/extra.css'

nav:
  - Home: 'index.md'
  - Getting Started: 'getting_started.md'
  - FAQ:
    - 'Features':
      - 'Geocoding': 'faq/features/geocoding.md'
      - 'Inventory Management': 'faq/features/inventory_management.md'
      - 'Miscellaneous': 'faq/features/misc.md'
    - 'Getting Help': 'faq/getting_help.md'
    - 'Hosting': 'faq/hosting.md'
    - 'Industry Involvement': 'faq/industry_involvement.md'
    - 'Security': 'faq/security.md'
  - User Documentation: 'documentation.md'
  - Developer Documentation: 'developer_resources.md'
  - Known Issues: 'known_issues.md'
  - References: 'references.md'
  - Release Notes: 'release_notes.md'
  - SEED Technical Allies: 'technical_ally.md'
